Repository onosproject/onos-lib-go, pull requests merged in 2020-02, with the labels that each got.

#4 Moved common gRPC Nothhbound out to this shared library
  go.mod
  go.sum
  pkg/certs/clientcerts.go
  pkg/certs/default-certificates.go
  pkg/northbound/client.go
  pkg/northbound/server.go
Labels: enhancement

#2 Hierarchical logging using Zap
  docs/logging.md
  go.mod
  go.sum
  pkg/logging/configuration.go
  pkg/logging/defs.go
  pkg/logging/logger.go
  pkg/logging/logger_test.go
  pkg/logging/util.go
  pkg/northbound/server.go
Labels: enhancement

#5 Increase the level abstractions for the logger
  docs/logging.md
  pkg/logging/logger.go
  pkg/logging/logger_test.go
  pkg/northbound/server.go
Labels: enhancement

#6 Spread the args to the lower level api
  pkg/logging/logger.go
Labels: bug

#8 Add caller info to the default configuration
  pkg/logging/configuration.go
  pkg/logging/logger.go
Labels: DO_NOT_MERGE

#10 Added in some base functions for CLI that are common to other modules
  go.mod
  go.sum
  pkg/cli/cli_test.go
  pkg/cli/client.go
  pkg/cli/config.go
  pkg/cli/output.go
Labels: enhancement

#9 Kafka Integration
  docs/logging.md
  go.mod
  go.sum
  pkg/logging/configuration.go
  pkg/logging/defs.go
  pkg/logging/kafka.go
  pkg/logging/logger.go
  pkg/logging/util.go
Labels: enhancement
